version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=prueba_tecnica

    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./database:/prueba_tecnica_dump.sql:docker-entrypoint-initdb.d/
    logging:
      driver: none

  app:
    container_name: app
    depends_on:
      - mysql
    restart: unless-stopped
    env_file: ./.env
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=prueba_tecnica
      - DB_PORT=3306
    stdin_open: true
    tty: true
    volumes:
      - ./:/app

volumes:
  mysql: